### ISSUE TITLE
Is it support chart representation from the results ? 

### ISSUE THREAD

**Issue by nvcken** [CarlosMatheus/Cloud-Benchmark#1]

**Comment by CarlosMatheus** [comment]
Hello, nvcken

I am currently working on treating results and plotting it.

So chart representation from the results will be available soon.

**Comment by CarlosMatheus** [comment]
Hi, nvcken

Recently I created one script to treat the data, so just run `treat_results.py` to get the a folder `treated_results` with csv files.

In order to make plots of the results, I didn't create a generic interface yet. But you can adapt the`plot_treated_results.py` to your use.

**Comment by nvcken** [comment]
Great thanks
